name = "bg_jobs"
version = "0.4.0"
gleam = ">= 1.4.0"

description = "Background job processing for your Gleam app"
licences = ["Apache-2.0"]
repository = { type = "github", user = "MaxHill", repo = "bg_jobs" }

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_otp = ">= 0.12.0 and < 1.0.0"
gleam_erlang = ">= 0.26.0 and < 1.0.0"
gleam_json = ">= 1.0.1 and < 2.0.0"
youid = ">= 1.2.0 and < 2.0.0"
decode = ">= 0.2.1 and < 1.0.0"
singularity = ">= 0.1.1 and < 1.0.0"
logging = ">= 1.3.0 and < 2.0.0"
pprint = ">= 1.0.3 and < 2.0.0"
sqlight = ">= 0.9.1 and < 1.0.0"
pog = ">= 1.0.0 and < 2.0.0"
gtempo = ">= 5.0.2 and < 6.0.0"
lamb = ">= 0.5.0 and < 1.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 2.0.0 and < 3.0.0"
envoy = ">= 1.0.2 and < 2.0.0"
